name: "Test Python Lib"
on:
  push:
    branches:
      - main
      - development
    pull_request:
    
permissions:
  contents: read
  pull-requests: read

jobs:
  run-pytest-linux:
    runs-on: ubuntu-latest  # windows-latest, macos-latest
    steps:
      - name: Show files
        run: ls -lt

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install poetry
        run: pip install poetry

      - name: Change path
        run: cd python-lib

      - name: Show files
        run: ls -lt

      - name: Install lib
        run: poetry install

      - name: Run pytest
        run: poetry run pytest
