name: "Test Python Lib"
on:
  push:
    branches:
      - main
      - development
    pull_request:
    
permissions:
  contents: read
  pull-requests: read

jobs:
  run-pytest-linux:
    runs-on: ubuntu-latest  # windows-latest, macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install poetry
        run: pip install poetry

      - name: Install lib
        run: |
          cd python-lib
          poetry install

      - name: Run pytest
        run: |
          cd python-ib
          poetry run pytest
